### ISSUE TITLE
How_to_Search_and_Load_Zarr_Stores.ipynb notebook is broken

### ISSUE THREAD

**Issue by christine-e-smit** [nasa/gesdisc-tutorials#95]
It looks like How_to_Search_and_Load_Zarr_Stores.ipynb is broken: https://github.com/nasa/gesdisc-tutorials/blob/main/cloud-tutorials/notebooks/How_to_Search_and_Load_Zarr_Stores.ipynb. Yikes! It looks like your rebase broke the notebook because the previous commit loads fine (https://github.com/nasa/gesdisc-tutorials/blob/a6921f673ef52b46f2e83e526927c0841787c1ba/cloud-tutorials/notebooks/How_to_Search_and_Load_Zarr_Stores.ipynb).

**Comment by christine-e-smit** [comment]
This is actually pretty high priority to fix because the howto link (https://disc.gsfc.nasa.gov/information/howto?keywords=zarr&title=How%20to%20Search%20and%20Access%20Giovanni%20Variable%20Zarr%20Stores) is the only one I included for documentation in last week's SciPy presentation. I'm happy to submit a pull request, but I don't know if you just want to roll back the change.

**Comment by battistowx** [comment]
Linking to https://github.com/nasa/gesdisc-tutorials/pull/96

**Comment by battistowx** [comment]
Fixed! https://disc.gsfc.nasa.gov/information/howto?keywords=zarr&title=How%20to%20Search%20and%20Access%20Giovanni%20Variable%20Zarr%20Stores
